import json
import os


def _cell(cell_type: str, source: list, outputs=None) -> dict:
    """Create a notebook cell."""
    cell = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = outputs or []
    return cell


def _md(*lines) -> dict:
    return _cell("markdown", [l + "\n" for l in lines])


def _code(*lines) -> dict:
    return _cell("code", [l + "\n" for l in lines[:-1]] + [lines[-1]])


def generate_notebook(result: dict, job_id: str, dataset_path: str,
                      learning_objective: str) -> str:
    """Generate a Jupyter notebook from pipeline results."""

    profiling      = result.get("profiling_report", {}) or {}
    imputation     = result.get("imputation_report", {}) or {}
    outlier        = result.get("outlier_report", {}) or {}
    encoding       = result.get("encoding_report", {}) or {}
    transformation = result.get("transformation_report", {}) or {}
    dimensionality = result.get("dimensionality_report", {}) or {}
    sampling       = result.get("sampling_report", {}) or {}
    quality        = result.get("quality_score", {}) or {}

    shape_orig  = profiling.get("shape", {})
    df_final    = result.get("processed_dataframe")
    shape_final = {"rows": df_final.shape[0], "columns": df_final.shape[1]} if df_final is not None else {}
    agents_run  = result.get("agents_to_run", []) or []
    orig_filename = os.path.basename(dataset_path)

    cells = []

    # ── TITLE ────────────────────────────────────────────────────────────
    cells.append(_md(
        f"# 🤖 Multi-Agent Data Preprocessing Report",
        f"",
        f"**Dataset:** `{orig_filename}`  ",
        f"**Learning Objective:** `{learning_objective}`  ",
        f"**Job ID:** `{job_id}`  ",
        f"",
        f"| | Before | After |",
        f"|---|---|---|",
        f"| Shape | {shape_orig.get('rows','?')} × {shape_orig.get('columns','?')} | {shape_final.get('rows','?')} × {shape_final.get('columns','?')} |",
        f"| Quality Score | {quality.get('total_before','?')} | {quality.get('total_after','?')} ({quality.get('grade_after',{}).get('label','')}) |",
        f"",
        f"**Agents Run:** {', '.join(agents_run) if agents_run else 'See below'}",
        f"",
        f"---",
        f"*Generated by Multi-Agent DataPrep System · LLaMA 3.3 70B via Groq*"
    ))

    # ── IMPORTS ───────────────────────────────────────────────────────────
    cells.append(_md("## 📦 1. Import Libraries"))
    cells.append(_code(
        "import pandas as pd",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "import seaborn as sns",
        "from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler",
        "import warnings",
        "warnings.filterwarnings('ignore')",
        "",
        "# Display settings",
        "pd.set_option('display.max_columns', None)",
        "pd.set_option('display.float_format', '{:.4f}'.format)",
        "print('✅ Libraries imported')"
    ))

    # ── LOAD DATA ─────────────────────────────────────────────────────────
    cells.append(_md("## 📂 2. Load Dataset"))
    cells.append(_code(
        f"df = pd.read_csv('{orig_filename}')",
        f"print(f'Dataset loaded: {{df.shape[0]}} rows × {{df.shape[1]}} columns')",
        f"df.head()"
    ))

    cells.append(_code(
        "# Quick overview",
        "print('Shape:', df.shape)",
        "print('\\nData types:')",
        "print(df.dtypes)",
        "print('\\nMissing values:')",
        "print(df.isnull().sum())"
    ))

    # ── PROFILING ─────────────────────────────────────────────────────────
    if profiling:
        num_cols  = profiling.get("numerical_columns", {})
        cat_cols  = profiling.get("categorical_columns", {})
        missing   = profiling.get("missing_values", {})
        insights  = profiling.get("insights", "")

        cells.append(_md(
            "## 🔍 3. Data Profiling",
            "",
            f"- **Numerical columns:** {len(num_cols)}",
            f"- **Categorical columns:** {len(cat_cols)}",
            f"- **Columns with missing values:** {len(missing)}",
            f"- **Duplicate rows:** {profiling.get('duplicate_rows', 0)}",
            "",
            f"**LLM Insights:** {insights[:500] if insights else 'N/A'}"
        ))
        cells.append(_code(
            "# Statistical summary",
            "df.describe()"
        ))
        if num_cols:
            cells.append(_code(
                "# Distribution plots for numerical columns",
                f"num_cols = {list(num_cols.keys())}",
                "fig, axes = plt.subplots(2, max(1, len(num_cols)//2 + len(num_cols)%2), figsize=(15, 6))",
                "axes = axes.flatten()",
                "for i, col in enumerate(num_cols):",
                "    if i < len(axes):",
                "        axes[i].hist(df[col].dropna(), bins=30, color='#4d9fff', alpha=0.7, edgecolor='white')",
                "        axes[i].set_title(col, fontsize=10)",
                "        axes[i].set_facecolor('#0b0f1a')",
                "        axes[i].tick_params(colors='gray')",
                "fig.patch.set_facecolor('#060810')",
                "plt.suptitle('Feature Distributions (Before Preprocessing)', color='white', fontsize=13)",
                "plt.tight_layout()",
                "plt.show()"
            ))

    # ── IMPUTATION ────────────────────────────────────────────────────────
    imp_status = imputation.get("status", "skipped")
    imp_actions = imputation.get("actions_taken", {}) or {}

    cells.append(_md(
        "## 🩹 4. Missing Value Imputation",
        "",
        f"**Status:** `{imp_status}`",
        "" if imp_status == "skipped" else f"**Columns treated:** {len(imp_actions)}"
    ))

    if imp_status == "completed" and imp_actions:
        imp_lines = ["# Missing value imputation"]
        for col, strategy in imp_actions.items():
            if "mean" in str(strategy).lower():
                imp_lines.append(f"df['{col}'].fillna(df['{col}'].mean(), inplace=True)")
            elif "median" in str(strategy).lower():
                imp_lines.append(f"df['{col}'].fillna(df['{col}'].median(), inplace=True)")
            elif "mode" in str(strategy).lower():
                imp_lines.append(f"df['{col}'].fillna(df['{col}'].mode()[0], inplace=True)")
            elif "drop" in str(strategy).lower():
                imp_lines.append(f"df.dropna(subset=['{col}'], inplace=True)")
            else:
                imp_lines.append(f"# {col}: {strategy}")
        imp_lines.append("print(f'Missing values remaining: {df.isnull().sum().sum()}')")
        cells.append(_code(*imp_lines))
    else:
        cells.append(_code(
            "# No missing values found — skipping imputation",
            "print(f'Missing values: {df.isnull().sum().sum()}')"
        ))

    # ── OUTLIER ───────────────────────────────────────────────────────────
    out_status  = outlier.get("status", "skipped")
    out_actions = outlier.get("actions_taken", {}) or {}
    out_info    = outlier.get("outlier_info", {}) or {}

    cells.append(_md(
        "## 📊 5. Outlier Detection & Handling",
        "",
        f"**Status:** `{out_status}`",
        "" if out_status == "skipped" else
        f"**Rows before:** {outlier.get('rows_before','?')} → **Rows after:** {outlier.get('rows_after','?')}"
    ))

    if out_status == "completed" and out_actions:
        out_lines = ["# Outlier handling"]
        for col, action in out_actions.items():
            info = out_info.get(col, {})
            if "Winsorized" in str(action):
                lb = info.get("lower_bound", 0)
                ub = info.get("upper_bound", 0)
                out_lines.append(f"df['{col}'] = df['{col}'].clip(lower={lb}, upper={ub})")
            elif "Log" in str(action):
                out_lines.append(f"df['{col}'] = np.log(df['{col}'] + 1)  # log transform")
            elif "Dropped" in str(action):
                lb = info.get("lower_bound", 0)
                ub = info.get("upper_bound", 0)
                out_lines.append(f"df = df[(df['{col}'] >= {lb}) & (df['{col}'] <= {ub})]")
            else:
                out_lines.append(f"# {col}: kept as-is")
        out_lines.append("print(f'Shape after outlier handling: {df.shape}')")
        cells.append(_code(*out_lines))
    else:
        cells.append(_code(
            "# No outliers detected or outlier handling skipped",
            "print('Skipped — no significant outliers found')"
        ))

    # ── ENCODING ──────────────────────────────────────────────────────────
    enc_status   = encoding.get("status", "skipped")
    enc_strategies = encoding.get("strategies_used", {}) or {}

    cells.append(_md(
        "## 🔤 6. Categorical Encoding",
        "",
        f"**Status:** `{enc_status}`",
        "" if enc_status == "skipped" else
        f"**Columns encoded:** {len(enc_strategies)}  \n"
        f"**Shape:** {encoding.get('shape_before','?')} → {encoding.get('shape_after','?')}"
    ))

    if enc_status == "completed" and enc_strategies:
        enc_lines = ["# Categorical encoding"]
        onehot_cols = [c for c, s in enc_strategies.items() if s == "onehot"]
        label_cols  = [c for c, s in enc_strategies.items() if s == "label"]
        freq_cols   = [c for c, s in enc_strategies.items() if s == "frequency"]
        drop_cols   = [c for c, s in enc_strategies.items() if s == "drop"]

        if onehot_cols:
            enc_lines.append(f"df = pd.get_dummies(df, columns={onehot_cols}, drop_first=False)")
        if label_cols:
            enc_lines.append("from sklearn.preprocessing import LabelEncoder")
            enc_lines.append("le = LabelEncoder()")
            for col in label_cols:
                enc_lines.append(f"df['{col}'] = le.fit_transform(df['{col}'].astype(str))")
        if freq_cols:
            for col in freq_cols:
                enc_lines.append(f"freq_map = df['{col}'].value_counts(normalize=True).to_dict()")
                enc_lines.append(f"df['{col}'] = df['{col}'].map(freq_map)")
        if drop_cols:
            enc_lines.append(f"df.drop(columns={drop_cols}, inplace=True, errors='ignore')")

        enc_lines.append("print(f'Shape after encoding: {df.shape}')")
        cells.append(_code(*enc_lines))
    else:
        cells.append(_code(
            "# No categorical columns to encode",
            "print('Skipped — no categorical columns')"
        ))

    # ── TRANSFORMATION ────────────────────────────────────────────────────
    trans_status     = transformation.get("status", "skipped")
    trans_strategies = transformation.get("strategies_used", {}) or {}
    trans_actions    = transformation.get("actions_taken", {}) or {}

    cells.append(_md(
        "## ⚖️ 7. Feature Transformation & Scaling",
        "",
        f"**Status:** `{trans_status}`",
        "" if trans_status == "skipped" else
        f"**Columns transformed:** {len(trans_actions)}"
    ))

    if trans_status == "completed" and trans_strategies:
        std_cols    = [c for c, s in trans_strategies.items() if s == "standard_scaler"]
        minmax_cols = [c for c, s in trans_strategies.items() if s == "minmax_scaler"]
        robust_cols = [c for c, s in trans_strategies.items() if s == "robust_scaler"]
        log_cols    = [c for c, s in trans_strategies.items() if s == "log_transform"]

        trans_lines = ["# Feature scaling and transformation"]
        if std_cols:
            trans_lines += [
                "from sklearn.preprocessing import StandardScaler",
                f"std_cols = {std_cols}",
                "std_scaler = StandardScaler()",
                "df[std_cols] = std_scaler.fit_transform(df[std_cols])",
                "print(f'Standard scaled: {std_cols}')"
            ]
        if robust_cols:
            trans_lines += [
                "from sklearn.preprocessing import RobustScaler",
                f"robust_cols = {robust_cols}",
                "robust_scaler = RobustScaler()",
                "df[robust_cols] = robust_scaler.fit_transform(df[robust_cols])",
                "print(f'Robust scaled: {robust_cols}')"
            ]
        if minmax_cols:
            trans_lines += [
                "from sklearn.preprocessing import MinMaxScaler",
                f"minmax_cols = {minmax_cols}",
                "minmax_scaler = MinMaxScaler()",
                "df[minmax_cols] = minmax_scaler.fit_transform(df[minmax_cols])",
                "print(f'MinMax scaled: {minmax_cols}')"
            ]
        if log_cols:
            for col in log_cols:
                trans_lines.append(f"df['{col}'] = np.log(df['{col}'] + 1)  # log transform")
            trans_lines.append(f"print(f'Log transformed: {log_cols}')")

        trans_lines.append("print(f'Shape after transformation: {df.shape}')")
        cells.append(_code(*trans_lines))
    else:
        cells.append(_code(
            "# No transformation applied",
            "print('Skipped — no numerical columns to transform')"
        ))

    # ── DIMENSIONALITY ────────────────────────────────────────────────────
    dim_status = dimensionality.get("status", "skipped") if dimensionality else "skipped"

    cells.append(_md(
        "## 📐 8. Dimensionality Reduction",
        "",
        f"**Status:** `{dim_status}`",
        f"**Reason:** {dimensionality.get('reason', 'Not needed') if dimensionality else 'Not needed'}"
    ))

    if dim_status == "completed" and dimensionality:
        strategy = dimensionality.get("strategy", "pca")
        n_after  = dimensionality.get("features_after", 10)
        dim_lines = [f"# Dimensionality reduction — {strategy}"]
        if strategy == "pca":
            dim_lines += [
                "from sklearn.decomposition import PCA",
                f"pca = PCA(n_components={n_after})",
                "num_cols_dim = df.select_dtypes(include='number').columns.tolist()",
                "df_pca = pca.fit_transform(df[num_cols_dim])",
                f"pca_cols = [f'PC{{i+1}}' for i in range({n_after})]",
                "df_pca = pd.DataFrame(df_pca, columns=pca_cols)",
                "print(f'PCA reduced to {n_after} components')",
                f"print(f'Variance explained: {{pca.explained_variance_ratio_.sum():.2%}}')"
            ]
        else:
            dim_lines.append("# SelectKBest applied during pipeline")
        cells.append(_code(*dim_lines))
    else:
        cells.append(_code(
            "# Dimensionality reduction not needed",
            "print('Skipped — feature count within acceptable range')"
        ))

    # ── SAMPLING ──────────────────────────────────────────────────────────
    samp_status   = sampling.get("status", "skipped") if sampling else "skipped"
    samp_strategy = sampling.get("strategy", "none") if sampling else "none"

    cells.append(_md(
        "## 🔁 9. Class Balancing (Sampling)",
        "",
        f"**Status:** `{samp_status}`",
        f"**Strategy:** `{samp_strategy}`"
    ))

    if samp_status == "completed" and samp_strategy != "none":
        target = sampling.get("target_column", "target")
        samp_lines = [f"# Class balancing — {samp_strategy}"]
        if samp_strategy == "smote":
            samp_lines += [
                "from imblearn.over_sampling import SMOTE",
                f"feature_cols = [c for c in df.columns if c != '{target}']",
                f"X, y = df[feature_cols], df['{target}']",
                "smote = SMOTE(random_state=42)",
                "X_res, y_res = smote.fit_resample(X, y)",
                "df = pd.DataFrame(X_res, columns=feature_cols)",
                f"df['{target}'] = y_res",
                "print(f'After SMOTE: {df.shape}')"
            ]
        elif samp_strategy == "oversample":
            samp_lines += [
                f"# Random oversampling of minority class in '{target}'",
                f"majority = df[df['{target}'] == df['{target}'].value_counts().index[0]]",
                f"minority = df[df['{target}'] != df['{target}'].value_counts().index[0]]",
                "minority_up = minority.sample(len(majority), replace=True, random_state=42)",
                "df = pd.concat([majority, minority_up]).sample(frac=1, random_state=42).reset_index(drop=True)",
                "print(f'After oversampling: {df.shape}')"
            ]
        elif samp_strategy == "undersample":
            samp_lines += [
                f"# Random undersampling of majority class in '{target}'",
                f"minority_count = df['{target}'].value_counts().min()",
                f"df = df.groupby('{target}').sample(n=minority_count, random_state=42).reset_index(drop=True)",
                "print(f'After undersampling: {df.shape}')"
            ]
        cells.append(_code(*samp_lines))
    else:
        cells.append(_code(
            "# Sampling not needed",
            f"print('Skipped — {samp_strategy if samp_status == 'skipped' else 'classes balanced'}')"
        ))

    # ── FINAL OVERVIEW ────────────────────────────────────────────────────
    cells.append(_md(
        "## ✅ 10. Final Dataset Overview",
        "",
        f"**Original shape:** {shape_orig.get('rows','?')} × {shape_orig.get('columns','?')}  ",
        f"**Final shape:** {shape_final.get('rows','?')} × {shape_final.get('columns','?')}  ",
        "",
        f"**Data Quality Score:** {quality.get('total_before','?')} → **{quality.get('total_after','?')}** ({quality.get('grade_after',{}).get('label','')})"
    ))

    cells.append(_code(
        "print('Final dataset shape:', df.shape)",
        "print('Missing values:', df.isnull().sum().sum())",
        "print('\\nColumn types:')",
        "print(df.dtypes)",
        "df.head()"
    ))

    cells.append(_code(
        "# Final distribution plots",
        "num_cols_final = df.select_dtypes(include='number').columns.tolist()[:8]",
        "if num_cols_final:",
        "    fig, axes = plt.subplots(2, max(1, len(num_cols_final)//2 + len(num_cols_final)%2), figsize=(15, 6))",
        "    axes = axes.flatten()",
        "    for i, col in enumerate(num_cols_final):",
        "        if i < len(axes):",
        "            axes[i].hist(df[col].dropna(), bins=30, color='#00d68f', alpha=0.7, edgecolor='white')",
        "            axes[i].set_title(col, fontsize=10)",
        "            axes[i].set_facecolor('#0b0f1a')",
        "            axes[i].tick_params(colors='gray')",
        "    fig.patch.set_facecolor('#060810')",
        "    plt.suptitle('Feature Distributions (After Preprocessing)', color='white', fontsize=13)",
        "    plt.tight_layout()",
        "    plt.show()"
    ))

    # ── SAVE ──────────────────────────────────────────────────────────────
    cells.append(_md("## 💾 11. Save Preprocessed Dataset"))
    cells.append(_code(
        "output_path = 'preprocessed_dataset.csv'",
        "df.to_csv(output_path, index=False)",
        "print(f'✅ Saved to {output_path}')",
        "print(f'Final shape: {df.shape}')"
    ))

    # ── ASSEMBLE NOTEBOOK ─────────────────────────────────────────────────
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": cells
    }

    return json.dumps(notebook, indent=2)